stages:
  - build
  - deploy

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r $CI_PROJECT_DIR/* .public
    - ls -ltr .public
    - mv .public public
  artifacts:
    paths:
      - public
